### ISSUE TITLE
Accept single path index for incremental merkle tree proofs

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#104]
In the [sparse merkle tree circuit](https://github.com/Unirep/Unirep/blob/main/packages/circuits/circuits/sparseMerkleTree.circom#L22) we accept the index of the leaf element and determine whether parent elements are left or right by converting the index to binary.

In the incremental merkle tree we instead accept a list of 1's and 0's indicating this. We should be able to replace this list with a single input argument that is the leaf element index. This will remove 1 constraint per depth (e.g. tree of depth 32 = 32 constraints removed).

Related #103

**Comment by ChialiTsai** [comment]
@vimwitch should we keep this issue open or close?

**Comment by ChialiTsai** [comment]
@vimwitch should we keep this issue open or close?

**Comment by vimwitch** [comment]
Definitely keep it

**Comment by vimwitch** [comment]
Closing, accepting the path index reduces the number of constraints.
