### ISSUE TITLE
Use self destructing contracts to store trees for each epoch

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#105]
We can't wipe mapping storage data without wiping the entire contract. One pattern we can use is having the unirep contract create a storage contract every epoch that contains the GST and epoch tree. Then at the end of the epoch we store the roots and selfdestruct the contract and create a new one.

This should help prevent us from taking too much space on the network.

**Comment by ChialiTsai** [comment]
@vimwitch do we still need this issue?
