### ISSUE TITLE
(Unirep/circuit) config use absolute path for import circuit and build folders

### ISSUE THREAD

**Issue by vuvoth** [Unirep/Unirep#124]
**Is your feature request related to a problem? Please describe.**
For now in Unirep/circuit we use relative path for link to [`zksnarkBuild`](https://github.com/Unirep/Unirep/blob/main/packages/circuits/provers/defaultProver.ts) or [`circuit`](https://github.com/Unirep/Unirep/blob/main/packages/circuits/test/proveReputation.test.ts#L18).
We should update it as absolute path, this make use easier to update and code base more clean.

**Describe the solution you'd like**
We can export the path in index.ts or config.ts and we can reuse absolute path .

**Describe alternatives you've considered**
Open to discuss....

**Additional context**

**Comment by vimwitch** [comment]
How would an absolute path look?

`path.join(__dirname, proveReputationCircuitPath)` is absolute, `__dirname` is the absolute path to the current file.

**Comment by vuvoth** [comment]
So I think this should be some think like `circuitPath` which absolute path to circuit folder. The reason is if we change don't want to create new `proveReputationCircuitPath` only need the name of circuit, same reason for zksnarkBuild.

**Comment by ChialiTsai** [comment]
Close issue because no longer need.
