### ISSUE TITLE
Use recursive circom proofs for UST

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#129]
Barry has said that recursive circom proofs are close to being ready to use. Once this is the case we should be able to rework a lot of our UST logic so that the bulk of it can be done by a server, then the user just proves that those proofs are valid plus some additional logic.

Related #128 (makes DOS less impactful because work can be delegated to large servers by non-users)

**Comment by ChialiTsai** [comment]
@vimwitch about this issue, do you think we need to tackle in short term?

**Comment by vimwitch** [comment]
No, we'll probably want to do this with PLONK, and circom support is still very poorly optimized and halo2 is not ready for use yet. Something we can do in the longer term.
