### ISSUE TITLE
Trusted setup ceremony

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#130]
We can run trusted setup with zkparty: https://trustedsetuptest.web.app/
Either run it ourselves: https://github.com/zkparty/trusted-setup-api or Geoff can help us
What we need to prepare:
1. circuit name
2. .r1cs file
3. ptau file

**Comment by ChialiT** [comment]
Closing this issue.
Ceremony has its own repo, will create issue over there.
