### ISSUE TITLE
Add circom in a docker image as a fallback

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#152]
If the user doesn't have `circom` in their `PATH` we should supply a docker image with the circom executable that can be used instead.

**Comment by vivianjeng** [comment]
I think it also requires user to install and open a docker server
so I prefer to guide them to install a [`circom 2`](https://docs.circom.io/getting-started/installation/)

**Comment by vimwitch** [comment]
We can do both. Lots of people already have docker + we use docker in our stack already. Iden3 doesn't distribute pre-built binaries for circom so it requires a manual build, which takes minutes on a powerful computer 🫤

**Comment by vimwitch** [comment]
Closing, we have a prebuilt circom binary on r2 that we use in ci
