### ISSUE TITLE
V1.1 contract test

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#163]
Build `@unirep/contracts` tests to cover all functions in `Unirep.sol`

**Comment by vivianjeng** [comment]
userSignUp
- [ ] success
- [ ] revert AttesterIdNotMatch()
- [ ] revert InvalidProof()
- [ ] revert AttesterNotSignUp()
- [ ] revert UserAlreadySignedUp()
- [ ] revert EpochNotMatch()
- [ ] state tree updates as expected
- [ ] semaphoreGroup updates as expected

attesterSignUp
- [ ] success
- [ ] revert AttesterAlreadySignUp()

attesterSignUpViaRelayer
- [ ] success
- [ ] revert InvalidSignature()
- [ ] revert AttesterAlreadySignUp()

submitAttestation
- [ ] success
- [ ] revert EpochNotMatch()
- [ ] revert InvalidEpochKey()

buildHashchain
- [ ] success
- [ ] revert when no attestations

processHashchain
- [ ] success
- [ ] revert InvalidProof()
- [ ] revert when `attesterId == 0`
- [ ] revert HashchainInvalid()
- [ ] revert InvalidEpochTreeRoot()

userStateTransition
- [ ] success
- [ ] revert InvalidProof()
- [ ] revert AttesterInvalid()
- [ ] revert NullifierAlreadyUsed()
- [ ] revert EpochNotMatch()
- [ ] revert HashchainNotProcessed()
- [ ] revert InvalidEpochTreeRoot()
- [ ] revert InvalidStateTreeRoot()
- [ ] state tree updates as expected

updateEpochIfNeeded
- [ ] success
- [ ] revert AttesterNotSignUp()
- [ ] epoch tree init correctly
- [ ] state tree init correctly

attesterCurrentEpoch
- [ ] success
- [ ] revert AttesterNotSignUp()

attesterEpochRemainingTime
- [ ] success
- [ ] revert AttesterNotSignUp()

attesterHashchainTotalCount
- [ ] success
- [ ] revert AttesterNotSignUp()

attesterHashchainProcessedCount
- [ ] sucess
- [ ] revert AttesterNotSignUp()

attesterHashchain
- [ ]  sucess
- [ ] revert AttesterNotSignUp()

attesterEpochLength
- [ ] success 
- [ ] revert AttesterNotSignUp()

attesterStateTreeRootExists
- [ ] success 
- [ ] revert AttesterNotSignUp()

attesterStateTreeRoot
- [ ] success 
- [ ] revert AttesterNotSignUp()

attesterStateTreeLeafCount
- [ ] success 
- [ ] revert AttesterNotSignUp()

attesterSemaphoreGroupRoot
- [ ] success 
- [ ] revert AttesterNotSignUp()

attesterEpochRoot
- [ ] success 
- [ ] revert AttesterNotSignUp()

stateTreeDepth
- [ ] success

epochTreeDepth
- [ ] success

numEpochKeyNoncePerEpoch
- [ ] success

**Comment by vimwitch** [comment]
We should try to improve the contract test coverage to 95%+. This is a good metric we can track. Our contract coverage is [~40%](https://app.circleci.com/pipelines/github/Unirep/Unirep/434/workflows/52e55bdb-4d23-46b0-84b7-65f412fd6139/jobs/2672?invite=true#step-106-162) right now.
