### ISSUE TITLE
Attester demosite

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#168]
We should make a webapp that can operate an attester. The user should be able to connect a wallet, register as an attester, and then operate identities in the context of the attester.

The user should be able to generate and verify all the proofs, submit attestations, process epoch key hashchains, and execute user state transitions.

We can use this as a demo site and for debugging. Maybe this could be incorporated into the `unirep.io` website later.

**Comment by ChialiT** [comment]
open this to other contributors in the core team.

**Comment by ChialiT** [comment]
@vimwitch can i close this issue since we have all the related efforts on create-unirep-app repo?

**Comment by ChialiT** [comment]
This is similar to the explorer project, open issue in explorer repo: https://github.com/Unirep/explorer/issues/13
