### ISSUE TITLE
Rep OAuth badge

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep#176]

**Comment by ChialiT** [comment]
@vimwitch we had this idea early on, it seems we can bring it back to backlog because of the "sign up with Unirep" project, what do you think?

**Comment by ChialiT** [comment]
maybe similar: https://github.com/kittybest/my-badge

**Comment by vivianjeng** [comment]
https://github.com/Unirep/Sign-up-with-Unirep
