### ISSUE TITLE
Prove many values in 1 field

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#181]
In the reputation proof and epoch proof there are lots of small public signals like `nonce`, `epoch`, `minRep`, and `proveGraffiti`. These signals can be combined into one signal by specifying ranges of bits that are dedicated to each value.

In a single 256 bit value we can reserve specific numbers of bits for each of these values to have fewer public signals (which will decrease the verification cost). One structure might be like this:

```
[64 bits epoch][8 bits nonce][128 bits minRep][8 bits proveGraffiti][52 bits zero]
```

[Here](https://github.com/vimwitch/zerocompress/blob/main/contracts/Decompress.sol#L22) I have a compression system that relied on bit operations. We can use code like this in the unirep contract to extract single binary values from individual fields. This becomes more useful as we make larger proofs around multiple epoch keys.

We can combine signals in other proofs as well if we define the `epoch` value to be 64 bit (we can also represent it using `Number` in javascript). This means that `epoch` and `attesterId` can be combined into a single signal (64 bits + 160 bits = 224 bits).

**Comment by kittybest** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/181?planning-poker) with Zenhub @kittybest

**Comment by ChialiTsai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/181?planning-poker) with Zenhub @vimwitch @vivianjeng @yuriko627 @AnthonyMadia @kittybest
