### ISSUE TITLE
Prove multiple epoch keys

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#182]
It would be useful to be able to prove information about multiple epoch keys from multiple epochs in a single proof.

For example, if I want to claim some reputation from a previous epoch (where I submitted an epoch key), I need to submit two proofs. One showing control of the old epoch key, one showing the new epoch key.

Having a single proof to show control of keys in different epochs solves this. One major problem with doing this, especially with reputation proofs, is the number of public signals. In a proof showing control of a past epoch key, and reputation in the current epoch, we have the following public signals:

```
oldEpochKey
oldEpoch
proveOldNonce
oldNonce

epoch
epochKey
proveGraffiti
minRep
proveNonce
nonce
```

We can combine a lot of these into a single field using #181

**Comment by vimwitch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/182?planning-poker) with Zenhub @AnthonyMadia @ChialiTsai @kittybest @vivianjeng @yuriko627

**Comment by ChialiTsai** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/182?planning-poker) with Zenhub @AnthonyMadia @kittybest @vimwitch @vivianjeng @yuriko627
