### ISSUE TITLE
`create-unirep-app` (contracts)

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#194]
Users can use `npx create-unirep-app` to get the boilerplate for a unirep application (an attester)
This issue will focus on its smart contract

**Comment by vivianjeng** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/194?planning-poker) with Zenhub @AnthonyMadia @kittybest @vimwitch @yuriko627 @ChialiTsai

**Comment by vimwitch** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/194?planning-poker) with Zenhub @vivianjeng

**Comment by vivianjeng** [comment]
https://github.com/Unirep/create-unirep-app/tree/main/packages/contracts
