### ISSUE TITLE
[core] Synchronizer handles hashchain events

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#249]
In #246 we add two hashchain events: `HashchainBuilt` and `HashchainProcessed`
These two events can be handled by synchronizer so that in the `genAggregateEpochKeysProof` it doesn't need to take the arguments like `hashchainIndex`(or set it as default value that can be queried from synchronizer db or contract)

**Comment by vimwitch** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/249?planning-poker) with Zenhub @CJ-Rose @AnthonyMadia @0xChiali @kittybest @vivianjeng
