### ISSUE TITLE
UI Changes

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#28]
Would be nice to experiment with the folllowing things:

- Hashtags/searches
- Permalinking
- [Rich previews for permalinks](https://www.pinata.cloud/blog/introducing-rich-previews-and-short-links) (Dynamic preview can be done in SSR)
- SSR
- Markdown preview for editor
- Color in the UI

**Comment by ChialiTsai** [comment]
want to convert these to a single individual issues?
right now we have the:
- Search
- rich text editor (markdown preview)


no premallinking - this is good to have for sharing
i dont understand whats SSR


maybe we can put the "color in UI" on hold.

**Comment by ChialiTsai** [comment]
close this ticket, because its duplicated in Unirep Social, some of items are already implemented.
