### ISSUE TITLE
Dashboard for invite codes

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#29]
We should build a small dashboard that will allow an admin to manage invite codes. This could start have the following:

A table with a list of users that have requested an invite code. Each cell should have:
- The user email
- The user metadata (profession, crypto experience, etc)
- A button to give them an invite code
- A button to reject the request

Inside the backend we should keep a list of users that have received invite codes. Ideally we don't keep emails on file for a long time. We could also store only the hash of the email.

**Comment by ChialiTsai** [comment]
we wont be doing invite code anymore, going to close this issue.
