### ISSUE TITLE
Remove `prover` from Synchronizer

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#336]
The `Synchronizer` doesn't generate proofs. Instead the `UserState` should accept the prover.

**Comment by vivianjeng** [comment]
I think it can generate the `genSealedEpochProof`
https://github.com/Unirep/Unirep/pull/332
and it doesn't (and shouldn't) require a user id

**Comment by vimwitch** [comment]
Now that we don't have `genSealedEpochProof` i think we can take the `prover` out of the synchronizer.
