### ISSUE TITLE
Combine timestamps in single field

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#355]
User data in unirep is currently structured as `[...sumFields, ...replaceFields]`. Each `replaceField` is 2 elements, the data, and the timestamp for the last field update. The timestamp is 64 bits so this structure has 190 bits unused.

Instead we can structure it like `[...sumFields, ...replaceFields, ...timestampFields]`, where each `timetampField` stores timestamps for 3 replacement fields. Each field is 64 bits so we can store 3 timestamps in a single field. This makes updating a replacement field potentially more cheap. e.g. if updating replacement field 1 and 2 only 1 timestamp field will need to be changed, instead of 2.

**Comment by ChialiT** [comment]
is this same as https://github.com/Unirep/Unirep/issues/337 ?
