### ISSUE TITLE
Allow user to define schema for data

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#356]
Right now we expose an array of 253 bit integers as user data. This is hard for applications to work with because they must manually encode/decode data. Instead we should write a class for encoding and parsing data according to a schema.

The schema should allow the following types:
- `uint[1-253]`: Unsigned integers of a specific bit width (e.g. `uint3` (0-7), `uint27` (0-134217728))
- `uint`: Alias for `uint253`
- `bool`: Alias for `uint1`

Each field should specify how it's updated, `sum` or `replace`. By default the fields should be updated by replacement.

The class should allow the following:
- decode `data` array to object
- encode an update as an attestation
- print info about field structure (e.g. what fields are at what data index)

When encoding updates the library should create the minimum number of transactions.

## Example schema

```js
[
  {
    name: 'posRep',
    type: 'uint64',
    updateBy: 'sum'
  },
  {
    name: 'negRep',
    type: 'uint64',
    updateBy: 'sum'
  },
  {
    name: 'graffiti',
    type: 'uint245',
  },
  {
    name: 'postCount',
    type: 'uint49',
    updateBy: 'sum'
  },
  {
    name: 'commentCount',
    type: 'uint49',
    updateBy: 'sum'
  }
  {
    name: 'voteCount',
    type: 'uint49',
    updateBy: 'sum'
  },
  {
    name: 'averageVote',
    type: 'uint8',
  },
]
```

This schema should result in the following:
```
sumData[0]: [posRep, negRep, postCount, commentCount],
sumData[1]: [voteCount],
replaceData[0]: [graffiti, averageVote]
```

An attestation updating `posRep` and `postCount` would involve changing only 1 field.

**Comment by ChialiT** [comment]
updateBy: - default value: 'replace'

**Comment by chndr1** [comment]
Should be 254 bits - replacement nonce bits right?

**Comment by vimwitch** [comment]
If `updateBy` is `replace` then the max type should be `253-replacementNonceBits`, yes

**Comment by chndr1** [comment]
Why is `[voteCount]` in `sumData[1]` whereas `[posRep, negRep, postCount, commentCount]` are in `sumData[0]`. Additionally, would there only need to be one `sumData` field and one 'replaceData' field no matter the number of sum or replacement fields described in the schema?
