### ISSUE TITLE
epoch key index should be queried from certain attester

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#397]
https://github.com/Unirep/Unirep/blob/f9b93993307435151c3362ea7c76093b0086e67e/packages/core/src/UserState.ts#L385-L387

user state transition will take `epochKeyLeafIndices` from `getEpochKeyIndex`
but it is not unique depends on how many attesters are synced
in this case
The `getEpochKeyIndex` should take an attester ID as input

**Comment by vimwitch** [comment]
Closed by #367
