### ISSUE TITLE
Re-use the `Pairing` library for zk proof verifiers

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#404]
Each verifier contract has it's own copy of the `Pairing` library for doing curve math. Instead we should deploy this library once and link it to each verifier contract. This will reduce the number of cold account accesses if multiple proofs are verified in a transaction.

**Comment by sorag20** [comment]
@vimwitch 
Hello,Can I work on it?

**Comment by vivianjeng** [comment]
@sorag20 yes!

**Comment by sorag20** [comment]
@vimwitch @vivianjeng
I think this issue is making the Pairing Library of gross16Verifier.txt independent as a contract, creating an interface and calling it in each verifier contract. Is this correct?

**Comment by vivianjeng** [comment]
@sorag20 
Yes
I think you can change the verifier template instead of changing each verifier

**Comment by sorag20** [comment]
> @sorag20 Yes I think you can change the verifier template instead of changing each verifier

@vivianjeng 
OK. Thank you !
