### ISSUE TITLE
Missing Range Checks on Comparison Circuits

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#417]
Some computations, such as comparisons, cannot be directly expressed as constraints in Circom. Instead, CircomLib provides templates that developers can use so that they don’t have to implement them from scratch. Importantly, some of these templates make assumptions about the inputs that the developers must enforce. The `LessThan(N)`, `LessEqThan(N)`, `GreaterThan(N)` and `GreaterEqThan(N)` templates are all examples of such library templates as they all assume that the inputs are all constrained to be within `N` bits. If this does not hold, the template output can be manipulated. As an example, consider the snippet below.

> Snippet of `EpochKeyLite` with an unsafe use of `LessThan`
> 
> 
> ```
> template EpochKeyLite(EPOCH_KEY_NONCE_PER_EPOCH) {
>     ...
> 
>     component nonce_lt = LessThan(8);
>     nonce_lt.in[0] <== nonce;
>     nonce_lt.in[1] <== EPOCH_KEY_NONCE_PER_EPOCH;
>     nonce_lt.out === 1;
> 
>     ...
> }
> ```
> 

The above code does not include a check that `nonce` is within the range of an 8 bit value. This allows a malicious user to manipulate the circuit by providing a very large `nonce`, say `P - 1`, causing an overflow in the `LessThan` circuit (where `P` is the large prime). This will result in the template improperly reporting that  `P - 1` is less than `EPOCH_KEY_NONCE_PER_EPOCH`.

## Impact

Several templates make extensive use of the comparator templates from CircomLib, including `ProveReputation`, `UserStateTransition` and `EpochKeyLite`. These circuits implement critical behaviors in the project and can be manipulated in ways the developers likely do not intend. For example, the above snippet is used to ensure that a user can only generate a limited number of keys within an epoch. Without the range check, users can generate about 255 more keys than intended.

## Recommendation

While a previous auditor recommended that some of these range checks should be removed to save constraints, their removal compromises the security of the system, especially when the inputs are private (as is the case with `nonce` above). Ensure that a range check is performed on all inputs to the comparator circuits.

**Comment by vimwitch** [comment]
Partially fixed [here](https://github.com/Unirep/Unirep/pull/412/commits/9934fe7be73675ddd3f1cec56a533875ec33a20b)
