### ISSUE TITLE
Synchronization takes a long time

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#445]
As time goes on synchronization takes longer. This is because the synchronizer loads sets of `blockRate` blocks in each loop. By default this is 100,000. So after 1 million blocks synchronization will take at least 10 seconds (assuming each load takes 1 second).

On mainnet this would be okay because 1 million blocks = ~139 days. On an L2 like arbitrum blocks are much more frequent so the synchronization takes longer.

We don't want to load too many blocks at once because there might be many events, but we don't want to load too few because then synchronization takes too long. It would be nice if we could request the first `n` events from a range of blocks but that doesn't seem to be possible.

Another approach might be loading the batches in parallel, but this puts more strain on the underlying server.

**Comment by vimwitch** [comment]
To solve this problem we should separate the event loading and processing.

Events should be loaded in parallel and stored in a FIFO queue. The event processing logic could work by loading the events for the next block in the queue and processing them. The processing loop continuously checks the queue for new events to process.

Note that events in the queue should be grouped by block. e.g. all events for a block are processed before the `SynchronizerState` in the database is updated.

Parallel requests should retry when failed using exponential backoff logic.

Make sure that parallel requests don't insert events out of order. e.g. if you're loading blocks 0-20 and 20-40 in parallel, blocks 20-40 cannot be inserted before 0-20.

**Comment by ChialiT** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/UniRep-protocol-6351bcd5d284ee2931d525aa/issues/Unirep/Unirep/445?planning-poker) with Zenhub @AnthonyMadia @chndr1 @CJ-Rose @kittybest @vimwitch @vivianjeng @yuriko627
