### ISSUE TITLE
[Audit medium severity] Potential Attestation Loss

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#456]
The Unirep protocol allows attesters to assert that changes should be made to the owners of particular epoch keys. Over the course of the epoch, these changes are recorded the attester’s `epochTree` which is a re-usable incremental merkle tree. When epochs expire, users are expected to apply the changes recorded in the `epochTree` by performing a state transition. To do so, however, the epoch tree root must be saved along with the state tree root in the history tree. In the `Unirep` contract, this is done when transitioning to a new epoch but only if an update has been made to the `stateTree`. Therefore, if no state tree update has been made the attestations are discarded.

> Location where the `epochTree` is reset
> 
> 
> ```solidity
>     function updateEpochIfNeeded(
>         uint160 attesterId
>     ) public returns (uint48 epoch) {
>         ...
> 
>         if (attester.stateTree.numberOfLeaves > 0) {
>             uint256 historyTreeLeaf = PoseidonT3.hash(
>                 [attester.stateTree.root, attester.epochTree.root]
>             );
>             uint256 root = IncrementalBinaryTree.insert(
>                 attester.historyTree,
>                 historyTreeLeaf
>             );
>             attester.historyTreeRoots[root] = true;
> 
>             ReusableMerkleTree.reset(attester.stateTree);
> 
>             attester.epochTreeRoots[fromEpoch] = attester.epochTree.root;
> 
>             emit HistoryTreeLeaf(attesterId, historyTreeLeaf);
>         }
> 
>         ReusableMerkleTree.reset(attester.epochTree);
> 
>         emit EpochEnded(epoch - 1, attesterId);
> 
>         attester.currentEpoch = epoch;
>     }
> ```
> 

## Impact

As the state tree is only changed when a user is added by the attester or when a user transitions state, it is possible for attestations to be lost. In particular, assuming no users are updated it is possible for current users of the protocol to collude to discard undesirable updates to the state (particularly if there are a small number of users). Since this epoch is essentially discarded and ignored, this users may then transition from the previous epoch to the next epoch (i.e. users may skip `e` to transition from `e-1` to `e+1`).

## Developer Response

It is expected that the attester will validate an epoch key before performing an attestation. As long as this is done properly, then the epoch tree will be empty if the state tree is empty.

**Comment by vivianjeng** [comment]
I think we can add revert in `attest`
if there is no leaves in the current state tree, the contract reverts the attestation.

**Comment by vimwitch** [comment]
Yes we could, it would add a cold `SLOAD` (a few thousand gas). I think a warning is sufficient for this, attesters should be aware of the epoch keys they're attesting to (e.g. validate that the epoch key exists in the state tree).
