### ISSUE TITLE
Circuits CI fails randomly

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#46]
**Describe the bug**
"prove reputation with incorrect reputation should fail" test scripts fails randomly

**To Reproduce**
1. See the circuits CI actions in GitHub 

**Expected behavior**
It should be passed all the time

**Comment by vimwitch** [comment]
[This](https://github.com/Unirep/Unirep/blob/master/packages/circuits/test/proveReputation.test.ts#L262) is causing the intermittent failures. Shared test state strikes again 😅
