### ISSUE TITLE
[Feature] enable attester to submit json file about their application info

### ISSUE THREAD

**Issue by ChialiT** [Unirep/Unirep#492]
- give ECDSA signature using attester deployer key
- sign JSON document to be shown for attester

**Comment by ChialiT** [comment]
@chndr1 & @vimwitch can u guys sync up on this feature? We would like to start enriching the explorer

**Comment by chndr1** [comment]
@ChialiT spoke to @vimwitch and it makes more sense for this issue to be under the explorer repo

**Comment by ChialiT** [comment]
> @ChialiT, I spoke to @vimwitch and it makes more sense for this issue to be under the explorer repo

You are right! I dropped in the issue too fast and it went to wrong place. thank you for correcting this.
