### ISSUE TITLE
Selecting unirep 2.0.0 default circuit configuration

### ISSUE THREAD

**Issue by vimwitch** [Unirep/Unirep#495]
This issue contains compiled circuit info for different configurations.

Default configuration

```js
    STATE_TREE_DEPTH: 17,
    EPOCH_TREE_DEPTH: 17,
    HISTORY_TREE_DEPTH: 17,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 2,
    FIELD_COUNT: 6, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```

```sh
User state transition proof
[INFO]  snarkJS: # of Constraints: 26540
Epoch key proof
[INFO]  snarkJS: # of Constraints: 6279
```

**Comment by vimwitch** [comment]
```js    
    STATE_TREE_DEPTH: 15,
    EPOCH_TREE_DEPTH: 15,
    HISTORY_TREE_DEPTH: 17,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 3,
    FIELD_COUNT: 6, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```

```sh
User state transition proof
[INFO]  snarkJS: # of Constraints: 31782
Epoch key proof
[INFO]  snarkJS: # of Constraints: 5793
```

**Comment by vimwitch** [comment]
```js
    STATE_TREE_DEPTH: 17,
    EPOCH_TREE_DEPTH: 17,
    HISTORY_TREE_DEPTH: 17,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 2,
    FIELD_COUNT: 7, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```
```sh
User state transition proof
[INFO]  snarkJS: # of Constraints: 28618
Epoch key proof
[INFO]  snarkJS: # of Constraints: 6519
```

**Comment by vimwitch** [comment]
```js
    STATE_TREE_DEPTH: 16,
    EPOCH_TREE_DEPTH: 16,
    HISTORY_TREE_DEPTH: 17,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 2,
    FIELD_COUNT: 8, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```
```sh
User state transition proof
[INFO]  snarkJS: # of Constraints: 29967
Epoch key proof
[INFO]  snarkJS: # of Constraints: 6516
```

**Comment by vimwitch** [comment]
```js
    STATE_TREE_DEPTH: 15,
    EPOCH_TREE_DEPTH: 15,
    HISTORY_TREE_DEPTH: 18,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 3,
    FIELD_COUNT: 4, // total number of fields
    SUM_FIELD_COUNT: 2, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```
```sh
User state transition proof
[INFO]  snarkJS: # of Constraints: 29607
Epoch key proof
[INFO]  snarkJS: # of Constraints: 5313
```

**Comment by vivianjeng** [comment]
## `bigComparators.circom`

### BigLessThan (not used)
```shell=
template instances: 13
non-linear constraints: 1289
linear constraints: 0
public inputs: 0
public outputs: 1
private inputs: 2
private outputs: 0
wires: 1286
labels: 3360
```

### BigGreaterThan (not used)
```shell=
template instances: 14
non-linear constraints: 1289
linear constraints: 0
public inputs: 0
public outputs: 1
private inputs: 2
private outputs: 0
wires: 1286
labels: 3363
```

### replFieldEqual(REPL_NONCE_BITS)

used in `proveReputation.circom`

Indifference between different `REPL_NONCE_BITS`
```shell=
template instances: 6
non-linear constraints: 508
linear constraints: 0
public inputs: 0
public outputs: 1
private inputs: 2
private outputs: 0
wires: 509
labels: 1032
```

### LowerLessThan(n)

| n | non-linear constraints | 
| -------- | -------- | 
| 40 | 547     | 
| 50 | 557     | 
| 60 | 567     | 

### LowerGreaterThan(n)

used in `userStateTransition.circom`

| n | non-linear constraints | 
| -------- | -------- | 
| 40 | 547     | 
| 50 | 557     | 
| 60 | 567     | 

### ExtractBits(l, u)

```javascript=
assert(l + u <= 253);
```

| l | u | non-linear constraints | 
| -------- | -------- | -------- | 
| 40 | 213     | 253 |
| 50 | 203     | 253 |
| 60 | 193     | 253 |


## `Modulo.circom` (not used)

## `leafHasher.circom`

### EpochKeyHasher

used in `epochKey.circom`, `epochKeyLite.circom`,...

```shell=
template instances: 72
non-linear constraints: 240
linear constraints: 0
public inputs: 0
public outputs: 1
private inputs: 4
private outputs: 0
wires: 245
labels: 773
```

### EpochTreeLeaf(FIELD_COUNT)

used in `userStateTransition.circom`

| FIELD_COUNT | non-linear constraints | 
| -------- | -------- | 
| 6 | 1440     | 
| 7 | 1680     | 
| 8 | 1920     | 
| 9 | 2160     | 

### StateTreeLeaf(FIELD_COUNT)

used in `userStateTransition.circom`, `signup.circom`

| FIELD_COUNT | non-linear constraints | 
| -------- | -------- | 
| 6 | 1680     | 
| 7 | 1920     | 
| 8 | 2160     | 
| 9 | 2400     | 


## `identity.circom`

### IdentitySecret()
```shell=
template instances: 72
non-linear constraints: 240
linear constraints: 0
public inputs: 0
public outputs: 1
private inputs: 2
private outputs: 0
wires: 243
labels: 771
```

### IdentityCommitment()

used in `signup.circom`

```shell=
template instances: 142
non-linear constraints: 453
linear constraints: 0
public inputs: 0
public outputs: 2
private inputs: 2
private outputs: 0
wires: 456
labels: 1355
```

## `incrementalMerkleTree.circom`

### MerkleTreeInclusionProof(n_levels)

used in `userStateTransition.circom`, `epochKey.circom`,...

| n_levels | non-linear constraints | 
| -------- | -------- | 
| 10 | 2431     | 
| 12 | 2917     | 
| 14 | 3403     | 
| 16 | 3889     | 
| 20 | 4861     | 

## `signup.circom`

### Signup(FIELD_COUNT)

| FIELD_COUNT | non-linear constraints | 
| -------- | -------- | 
| 6 | 1138     | 
| 7 | 1138     | 

## `epochKeyLite.circom`

### EpochKeyLite(EPOCH_KEY_NONCE_PER_EPOCH)

| EPOCH_KEY_NONCE_PER_EPOCH | non-linear constraints | 
| -------- | -------- | 
| 2 | 467     | 
| 3 | 467     | 

## `epochKey.circom`

### EpochKey(STATE_TREE_DEPTH, EPOCH_KEY_NONCE_PER_EPOCH, FIELD_COUNT)

indifference if `Nonce` changed

| STATE_TREE | NONCE | FIELD | non-linear constraints | 
| -------- | -------- | -------- | -------- | 
| 16 | 2     | 6 | 6036 | 
| 17 | 2     | 6 | 6279 | 
| 18 | 2     | 6 | 6522 | 

| STATE_TREE | NONCE | FIELD | non-linear constraints | 
| -------- | -------- | -------- | -------- | 
| 16 | 2     | 6 | 6036 | 
| 16 | 2     | 7 | 6276 | 
| 16 | 2     | 8 | 6516 |


## `proveReputation.circom`

### ProveReputation(STATE_TREE_DEPTH, EPOCH_KEY_NONCE_PER_EPOCH, SUM_FIELD_COUNT, FIELD_COUNT, REPL_NONCE_BITS)

- change `STATE_TREE_DEPTH`

| STATE_TREE | NONCE | SUM_FIELD | FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | 
| **16** | 2     | 4 | 6 | 48 | 7160 |
| **17** | 2     | 4 | 6 | 48 | 7403 (+243) |
| **18** | 2     | 4 | 6 | 48 | 7646 (+243)|

- change `SUM_FIELD_COUNT`

| STATE_TREE | NONCE | SUM_FIELD | FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 2     | **4** | 6 | 48 | 7160 |
| 16 | 2     | **5** | 6 | 48 | 7160(+0) |

- change `FIELD_COUNT`

| STATE_TREE | NONCE | SUM_FIELD | FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 2     | 4 | **6** | 48 | 7160 |
| 16 | 2     | 4 | **7** | 48 | 7400 (+240) |
| 16 | 2     | 4 | **8** | 48 | 7640 (+240)|

- change `REPL_NONCE_BITS`

| STATE_TREE | NONCE | SUM_FIELD | FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 2     | 4 | 6 | **48** | 7160 |
| 16 | 2     | 4 | 6 | **50** | 7160 |


## `userStateTransition.circom`

### UserStateTransition

- change `STATE_TREE_DEPTH`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| **16** | 16     | 16 |  2 | 6 | 4 | 48 | 25568 | 
| **17** | 16     | 16 |  2 | 6 | 4 | 48 | 25811 (+243) | 
| **18** | 16     | 16 |  2 | 6 | 4 | 48 | 26054 (+243)| 


- change `EPOCH_TREE_DEPTH`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | **16**     | 16 |  2 | 6 | 4 | 48 | 25568 | 
| 16 | **17**     | 16 |  2 | 6 | 4 | 48 | 26054 (+486) | 

- change `HISTORY_TREE_DEPTH`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 16     | **16** |  2 | 6 | 4 | 48 | 25568 | 
| 16 | 16     | **17** |  2 | 6 | 4 | 48 | 25811 (+243) | 

- change `NONCE`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 16     | 16 |  **2** | 6 | 4 | 48 | 25568 | 
| 16 | 16     | 16 |  **3** | 6 | 4 | 48 | 32511 (+6943) | 
| 16 | 16     | 16 |  **4** | 6 | 4 | 48 | 39454 (+6943) | 

- change `FIELD`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 16     | 16 |  2 | **6** | 4 | 48 | 25568 | 
| 16 | 16     | 16 |  2 | **7** | 4 | 48 | 27646 (+2078) | 
| 16 | 16     | 16 |  2 | **8** | 4 | 48 | 29724 (+2078) | 

- change `SUM_FIELD`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 16     | 16 |  2 | 7 | **4** | 48 | 27646 |
| 16 | 16     | 16 |  2 | 7 | **5** | 48 | 26534 (-1112) |
| 16 | 16     | 16 |  2 | 7 | **6** | 48 | 25422 (-1112) |

- change `REPL_NONCE_BITS`

| STATE_TREE | EPOCH_TREE | HISTORY_TREE | NONCE | FIELD | SUM_FIELD | REPL_NONCE_BITS | non-linear constraints | 
| -------- | -------- | -------- | -------- | -------- | -------- | -------- | -------- | 
| 16 | 16     | 16 |  2 | 6 | 4 | **48** | 25568 |
| 16 | 16     | 16 |  2 | 6 | 4 | **50** | 25576 (+8) |
| 16 | 16     | 16 |  2 | 6 | 4 | **52** | 25584 (+8) |

**Comment by vivianjeng** [comment]
I think it is not too bad if we use maximum tree depths
though gas cost is high

```ts
    STATE_TREE_DEPTH: 32,
    EPOCH_TREE_DEPTH: 32,
    HISTORY_TREE_DEPTH: 32,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 5,
    FIELD_COUNT: 6, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```
constraints: 73613
Gen Proof time: 3815 ms (3 s)
Verification time: 134 ms (0 s)

**Gas cost**
- deployment: 3384205 (16184 bytes)
- `attesterSignup`: 258172
- `signup()`: 3988326, 2278572, 2277111, 4401674, 2245198, 2261317, 3217745, 2260158, 2248465
- `manualUserSignUp()`:  3896365
- `attest()`: 219758
- `userStateTransition()`: 3573606
- Average update cost (lazy): 121208.59469026548
- Average update cost (normal): 188372.98230088496

---

```ts
    STATE_TREE_DEPTH: 17,
    EPOCH_TREE_DEPTH: 17,
    HISTORY_TREE_DEPTH: 17,
    NUM_EPOCH_KEY_NONCE_PER_EPOCH: 2,
    FIELD_COUNT: 6, // total number of fields
    SUM_FIELD_COUNT: 4, // number of fields combined using addition
    REPL_NONCE_BITS: 48,
```
constraints: 26540
Gen Proof time: 1535 ms (1 s)
Verification time: 130 ms (0 s)

**Gas cost**
- deployment: 3384205 (16184 bytes)
- `attesterSignup`: 257137
- `signup()`: 2211543, 1313361, 1311828, 2470915, 1279939, 1296071, 1842022, 1294876, 1283206
- `manualUserSignUp()`:  2119582
- `attest()`: 219758
- `userStateTransition()`: 2013361
- Average insert cost (lazy): 75086.30158730158
- Average insert cost (normal): 229793.38095238095
