### ISSUE TITLE
Update semaphore v4

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#541]
Simplified identity: The two old identity secrets (`trapdoor` and `nullifier`) have been replaced by 1 secret only (`secret`). So `identity commitment = hash(identity secret)`, and `nullifier hash = hash(scope, identity secret)`.

We can remove all identity `trapdoor` and `nullifier` to use only `secret`

**Comment by sheagrief** [comment]
Hi, may I work on this issue?

**Comment by vivianjeng** [comment]
Hi @sheagrief 
Yes you can 😄 
Please also update circuit inputs for generating correct proofs

Thank you!

**Comment by vivianjeng** [comment]
Hi @sheagrief 
Are you able to finish this issue by this week?
This is a little bit urgent since we will run trusted setup soon
Or I will solve this 🙏🏻

**Comment by sheagrief** [comment]
@vivianjeng 
It seems a bit difficult to finish by the end of the week.
Sorry, may I leave this?
