### ISSUE TITLE
InterRep user/attester sign up

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#63]
**Is your feature request related to a problem? Please describe.**
Use [InterRep](https://github.com/interep-project/interep.js) to prevent sybil attack
and identity the [levels (gold, silver, bronze)](https://docs.interep.link/technical-reference/reputation/intro) of users/attesters

**Describe the solution you'd like**
1. User signs up through InterRep (with semaphore `idCommitment`)
2. User generates a merkle tree proof to prove that `idCommitment` is one of the leaves in InterRep merkle tree
3. User submit merkle tree proof + `idCommitment` to Unirep contract
4. Unirep contract checks merkle tree proof matches one of the current InterRep merkle tree roots
5. Unirep contract marks the `idCommitment` is a signed up user in Unirep

If users want to get different levels in InterRep, users generate different merkle tree proofs in different InterRep merkle tree
e.g. user signs up as `twitter-silver` level, then Unirep checks the `twitter-silver` tree root in InterRep
([`getRoot`](https://github.com/interep-project/contracts/blob/main/contracts/Interep.sol#L71) from different `groupId` in InterRep)

**Comment by vimwitch** [comment]
Should this be a part of the Unirep core? Seems like it would be nice to have a utility that attesters could use to add verification parameters. e.g. user has a signup code _and_ is at least `github-bronze` or `twitter-bronze` or `reddit-bronze`.

Might be good to include this in the next version of unirep social, even just as a reference implementation for other attesters. I'd like to see the bronze levels be a bit lower though, 500 followers is a lot 😅

**Comment by vivianjeng** [comment]
Yeah I think it has to be in Unirep core
because our circuits cannot host more then `2**GSTDepth` users
and users can easily generate random number to sign up (even if they don't have the `ZKIdentity` itself)
But do you think every user should sign up through a signed up attester? (now it is not necessary)

yeah we can help attesters choose the root (`github-bronze`...) they want to sign up users

yeah I am even not any of the `bronze` users in InterRep 😅
I think we can discuss this with InterRep team and maybe set our `unirep-bronze`, `unirep-silver`... rules

**Comment by vimwitch** [comment]
I agree that DOS is a problem, especially when `GSTDepth` is small like `2**9`. Before we integrate some anti-sybil in the core protocol we should benchmark increasing `GSTDepth` to something like `2**32`. If the GST depth is high enough then filling the tree becomes very expensive. Though an attacker could still increase the sync time by signing up lots of identity commitments (still spending money to do so).

I'm just hesitant to add something as big as interrep to the core implementation, especially when attackers have no incentive to spend money to halt the system.

>  But do you think every user should sign up through a signed up attester? (now it is not necessary)

I don't really think it matters. If someone wants they can make themselves an attester and then sign themselves up. **But** when we have an attester whitelist i think we should only allow signup through attester.

**Comment by vivianjeng** [comment]
> we should benchmark increasing `GSTDepth` to something like `2**32`

We will also do this  https://github.com/Unirep/Unirep/issues/53
But in my experience it is almost not possible to increase to `2**32` and generate proofs in frontend (using wasm)

I think it is not reasonable for attackers to halt system but once Unirep contract is halted, our loss could be much more than the attackers' cost (because we will deploy contracts and what we pay for the honest users will be in vain)

> when we have an attester whitelist i think we should only allow signup through attester

so I think the whitelist can also be maintained by InterRep. Like we only let `twitter-silver` level organizations/user signs up as an attester ( I remember that Barry said about it)

**Comment by vimwitch** [comment]
Closing this as we decided this is an attester level feature
