### ISSUE TITLE
Deploy with existing Verifier addresses

### ISSUE THREAD

**Issue by vivianjeng** [Unirep/Unirep#66]
**Is your feature request related to a problem? Please describe.**
https://github.com/Unirep/Unirep/pull/58#discussion_r913072139
Deploy verifiers every time when deploy a new Unirep.
We can reuse the deployed verifiers if the verifiers are the same

**Describe the solution you'd like**
Deploy contracts with verifier addresses as inputs
If it is `undefined`, then deploy verifiers

**Describe alternatives you've considered**
https://github.com/Unirep/Unirep/pull/58#discussion_r913278761
it would be nice to write a deployer that can retrieve a verifier contract by config. E.g. hash the gst depth, ust depth, epoch tree deptch, etc, then key that to an address of a verifier. Ideally we'd do this with create2 but maybe it's not possible.

**Comment by ChialiTsai** [comment]
Should this one be closed? @vivianjeng

**Comment by vivianjeng** [comment]
not yet 😢

**Comment by vimwitch** [comment]
Closed by #372
